spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: stone
    url: jdbc:mysql://10.118.17.43/msdb?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell
  port: 8081
