spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: stone
    url: jdbc:mysql://192.168.31.68/wechat_order_system?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  # 若字段为是必需值, 则可以在DTO中设置一个默认的值
  # 若返回给前端的字段是非必需值,则可以做以下设置 来去掉返回结果为null的字段
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
  port: 8081
