spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: stone
    url: jdbc:mysql://192.168.0.111/wechat_order_system?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true